  listen 80;
{% if ipv6 -%}
  listen [::]:80;
{% else -%}
  #listen [::]:80;
{% endif %}
{% if certificate -%}
  listen {{ https_port | default: 443 }} ssl;
{% if ipv6 -%}
  listen [::]:{{ https_port | default: 443 }} ssl;
{% else -%}
  #listen [::]:{{ https_port | default: 443 }};
{% endif %}
{% endif %}
  server_name {{ domain_names | join: " " }};
{% if http2_support == 1 or http2_support == true %}
  http2 on;
{% else -%}
  http2 off;
{% endif %}